In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snb

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.7)

In [5]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)
model_lr.score(X_test, y_test)

c:\Users\Avinash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [6]:
model_svm = SVC()
model_svm.fit(X_train, y_train)
model_svm.score(X_test, y_test)

0.9814814814814815

In [7]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)
model_rf.score(X_test, y_test)

0.975925925925926

In [8]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)
    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [11]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

c:\Users\Avinash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [12]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.975925925925926

In [13]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9814814814814815

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [26]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    lr = get_score(LogisticRegression(), X_train, X_test, y_train, y_test)
    rf = get_score(RandomForestClassifier(n_estimators=400), X_train, X_test, y_train, y_test)
    svm = get_score(SVC(), X_train, X_test, y_train, y_test)

    scores_lr.append(lr)
    scores_rf.append(rf)
    scores_svm.append(svm)

c:\Users\Avinash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Avinash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.or

In [27]:
scores_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [28]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [29]:
scores_rf

[0.9382303839732888, 0.9532554257095158, 0.9248747913188647]

In [35]:
from sklearn.model_selection import cross_val_score

# cross_val_score(SVC(), digits.data, digits.target)
# cross_val_score(LogisticRegression(), digits.data, digits.target)
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.925     , 0.91666667, 0.9637883 , 0.9637883 , 0.91922006])